### ISSUE TITLE
Error when enabling plugin

### ISSUE THREAD

**Issue by jarissimo** [CookieBadger/assetplacer-docs#23]
Hi, 
i try to use AssetPlacer on Ubuntu 24.04.01 with Godot 4.3 Mono and .Net 8.0.
When enabling the plugin, I get following error message:

```
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.InvalidCastException: Unable to cast object of type 'Godot.Resource' to type 'AssetPlacer.AssetPlacerPluginData'.
     at Godot.ResourceLoader.Load[T](String path, String typeHint, CacheMode cacheMode) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Extensions/ResourceLoaderExtensions.cs:line 27
     at AssetPlacer.AssetPlacerPersistence.LoadPluginData() in /path/to/game/folder/addons/assetplacer/AssetPlacerPersistence.cs:line 127
     at AssetPlacer.AssetPlacerPersistence.Init() in /path/to/game/folder/addons/assetplacer/AssetPlacerPersistence.cs:line 33
     at AssetPlacer.AssetPlacerPlugin._Init() in /path/to/game/folder/addons/assetplacer/AssetPlacerPlugin.cs:line 113
     at AssetPlacer.ContextlessPlugin._EnterTree() in /path/to/game/folder/addons/assetplacer/utils/contextlessPlugin/ContextlessPlugin.cs:line 77
     at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 2365
     at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1417
     at AssetPlacer.ContextlessPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /path/to/game/folder/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/AssetPlacer.ContextlessPlugin_ScriptMethods.generated.cs:line 250
     at AssetPlacer.AssetPlacerPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /path/to/game/folder/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/AssetPlacer.AssetPlacerPlugin_ScriptMethods.generated.cs:line 450
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.NullReferenceException: Object reference not set to an instance of an object.
     at AssetPlacer.AssetPlacerPersistence.GetShowLicenseAndSetFalse() in /path/to/game/folder/addons/assetplacer/AssetPlacerPersistence.cs:line 152
     at AssetPlacer.AssetPlacerPlugin._EnablePlugin() in /path/to/game/folder/addons/assetplacer/AssetPlacerPlugin.cs:line 205
     at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1305
     at AssetPlacer.ContextlessPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /path/to/game/folder/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/AssetPlacer.ContextlessPlugin_ScriptMethods.generated.cs:line 250
     at AssetPlacer.AssetPlacerPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /path/to/game/folder/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/AssetPlacer.AssetPlacerPlugin_ScriptMethods.generated.cs:line 450
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.NullReferenceException: Object reference not set to an instance of an object.
     at AssetPlacer.AssetPlacerPlugin._ProcessUpdate(Double delta) in /path/to/game/folder/addons/assetplacer/AssetPlacerPlugin.cs:line 579
     at AssetPlacer.ContextlessPlugin._Process(Double delta) in /path/to/game/folder/addons/assetplacer/utils/contextlessPlugin/ContextlessPlugin.cs:line 165
     at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 2395
     at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1417
     at AssetPlacer.ContextlessPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /path/to/game/folder/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/AssetPlacer.ContextlessPlugin_ScriptMethods.generated.cs:line 250
     at AssetPlacer.AssetPlacerPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /path/to/game/folder/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/AssetPlacer.AssetPlacerPlugin_ScriptMethods.generated.cs:line 450
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
  AssetPlacerPlugin: Please reload Asset Placer Plugin from the Project Settings panel!
```

I added the plugin to the plugins folder, build with C# and then tried to enable it.

**Comment by CookieBadger** [comment]
Hi, thanks for the report, does this still occur in any of the later versions (4.4, or 4.5)?
