### ISSUE TITLE
Get Null Refs when selecting nodes

### ISSUE THREAD

**Issue by Jonasrah** [CookieBadger/assetplacer-docs#26]
I am getting the following:

`  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.NullReferenceException: Object reference not set to an instance of an object.
     at AssetPlacer.SurfacePlacementController.OnSelectionChanged() in /Users/jonas/Documents/Projects/Godot/Coordinate System/addons/assetplacer/placementController/SurfacePlacementController.cs:line 63
     at AssetPlacer.AssetPlacerPlugin.OnSelectionChanged() in /Users/jonas/Documents/Projects/Godot/Coordinate System/addons/assetplacer/AssetPlacerPlugin.cs:line 464
     at Godot.Callable.<From>g__Trampoline|1_0(Object delegateObj, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.generics.cs:line 39
     at Godot.DelegateUtils.InvokeWithVariantArgs(IntPtr delegateGCHandle, Void* trampoline, godot_variant** args, Int32 argc, godot_variant* outRet) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 86
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.NullReferenceException: Object reference not set to an instance of an object.
     at AssetPlacer.SurfacePlacementController.OnSelectionChanged() in /Users/jonas/Documents/Projects/Godot/Coordinate System/addons/assetplacer/placementController/SurfacePlacementController.cs:line 63
     at AssetPlacer.AssetPlacerPlugin.OnSelectionChanged() in /Users/jonas/Documents/Projects/Godot/Coordinate System/addons/assetplacer/AssetPlacerPlugin.cs:line 464
     at AssetPlacer.AssetPlacerPlugin.OnSceneChanged(Node root) in /Users/jonas/Documents/Projects/Godot/Coordinate System/addons/assetplacer/AssetPlacerPlugin.cs:line 509
     at Godot.EditorPlugin.SceneChangedTrampoline(Object delegateObj, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1035
     at Godot.DelegateUtils.InvokeWithVariantArgs(IntPtr delegateGCHandle, Void* trampoline, godot_variant** args, Int32 argc, godot_variant* outRet) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 86
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.NullReferenceException: Object reference not set to an instance of an object.
     at AssetPlacer.SurfacePlacementController.OnSelectionChanged() in /Users/jonas/Documents/Projects/Godot/Coordinate System/addons/assetplacer/placementController/SurfacePlacementController.cs:line 63
     at AssetPlacer.AssetPlacerPlugin.OnSelectionChanged() in /Users/jonas/Documents/Projects/Godot/Coordinate System/addons/assetplacer/AssetPlacerPlugin.cs:line 464
     at Godot.Callable.<From>g__Trampoline|1_0(Object delegateObj, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.generics.cs:line 39
     at Godot.DelegateUtils.InvokeWithVariantArgs(IntPtr delegateGCHandle, Void* trampoline, godot_variant** args, Int32 argc, godot_variant* outRet) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 86
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.NullReferenceException: Object reference not set to an instance of an object.
     at AssetPlacer.SurfacePlacementController.OnSelectionChanged() in /Users/jonas/Documents/Projects/Godot/Coordinate System/addons/assetplacer/placementController/SurfacePlacementController.cs:line 63
     at AssetPlacer.AssetPlacerPlugin.OnSelectionChanged() in /Users/jonas/Documents/Projects/Godot/Coordinate System/addons/assetplacer/AssetPlacerPlugin.cs:line 464
     at Godot.Callable.<From>g__Trampoline|1_0(Object delegateObj, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.generics.cs:line 39
     at Godot.DelegateUtils.InvokeWithVariantArgs(IntPtr delegateGCHandle, Void* trampoline, godot_variant** args, Int32 argc, godot_variant* outRet) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 86
  /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs:113 - System.NullReferenceException: Object reference not set to an instance of an object.
     at AssetPlacer.SurfacePlacementController.OnSelectionChanged() in /Users/jonas/Documents/Projects/Godot/Coordinate System/addons/assetplacer/placementController/SurfacePlacementController.cs:line 63
     at AssetPlacer.AssetPlacerPlugin.OnSelectionChanged() in /Users/jonas/Documents/Projects/Godot/Coordinate System/addons/assetplacer/AssetPlacerPlugin.cs:line 464
     at AssetPlacer.AssetPlacerPlugin.OnSceneChanged(Node root) in /Users/jonas/Documents/Projects/Godot/Coordinate System/addons/assetplacer/AssetPlacerPlugin.cs:line 509
     at Godot.EditorPlugin.SceneChangedTrampoline(Object delegateObj, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1035
     at Godot.DelegateUtils.InvokeWithVariantArgs(IntPtr delegateGCHandle, Void* trampoline, godot_variant** args, Int32 argc, godot_variant* outRet) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs:line 86`

Version is 14.0

**Comment by CookieBadger** [comment]
Thanks for reporting the issue. There seems to be an error with the surface placement controller when selecting objects. I will look into it and let you know once I have a fix.

**Comment by CookieBadger** [comment]
Testing this issue, I was wondering, does this issue persist when you disable and reenable the plugin? Or is the issue then gone (for a while).

**Comment by Jonasrah** [comment]
It disappears, and I haven’t encountered it for a while. I have to also say that it might be due to some internal corruptions in my project. I have since deleted the .godot folder, and things seem less error prone. I will let you know if I encounter the issue again later

Den 29. nov. 2024 kl. 22.40 skrev CookieBadger ***@***.***>:

﻿

Testing this issue, I was wondering, does this issue persist when you disable and reenable the plugin? Or is the issue then gone (for a while).

**Comment by CookieBadger** [comment]
Thanks for the info, in that case I'll close this. If the problem resurfaces again and impedes your development, feel free to open this again.

Best regards
