### ISSUE TITLE
Breaking Error on MacOS on Activation - NullReferenceException on Get3DViewports()

### ISSUE THREAD

**Issue by Muini** [CookieBadger/assetplacer-docs#4]
Hey there, 

I'm on 4.0.3 stable, macOS (silicon), mono

I cannot use the plugin, activating it gives me those errors:
```
Copying Godot Offline Packages...
  scene/main/node.cpp:1248 - Index p_index = 0 is out of bounds (data.children.size() - data.internal_children_front - data.internal_children_back = 0).
  modules/mono/glue/runtime_interop.cpp:1303 - System.NullReferenceException: Object reference not set to an instance of an object.
     at AssetPlacer.ContextlessPlugin.<>c.<Get3DViewports>b__20_0(Node vp) in /gamesrc/addons/assetplacer/utils/contextlessPlugin/ContextlessPlugin.cs:line 219
     at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
     at AssetPlacer.ContextlessPlugin._EnterTree() in /gamesrc/addons/assetplacer/utils/contextlessPlugin/ContextlessPlugin.cs:line 31
     at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 1777
     at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1293
     at AssetPlacer.ContextlessPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /gamesrc/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/AssetPlacer.ContextlessPlugin_ScriptMethods.generated.cs:line 145
     at AssetPlacer.AssetPlacerPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /gamesrc/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/AssetPlacer.AssetPlacerPlugin_ScriptMethods.generated.cs:line 271
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
  AssetPlacerPlugin: Please reload Asset Placer Plugin from the Project Settings panel!
  modules/mono/glue/runtime_interop.cpp:1303 - System.NullReferenceException: Object reference not set to an instance of an object.
     at AssetPlacer.AssetPlacerPlugin._ProcessUpdate(Double delta) in /gamesrc/addons/assetplacer/AssetPlacerPlugin.cs:line 468
     at AssetPlacer.ContextlessPlugin._Process(Double delta) in /gamesrc/addons/assetplacer/utils/contextlessPlugin/ContextlessPlugin.cs:line 151
     at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 1807
     at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1293
     at AssetPlacer.ContextlessPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /gamesrc/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/AssetPlacer.ContextlessPlugin_ScriptMethods.generated.cs:line 145
     at AssetPlacer.AssetPlacerPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /gamesrc/Godot.SourceGenerators/Godot.SourceGenerators.ScriptMethodsGenerator/AssetPlacer.AssetPlacerPlugin_ScriptMethods.generated.cs:line 271
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
  Transient parent has another exclusive child.

```

**Comment by CookieBadger** [comment]
Thank you very much for reporting this. This means, that the Editor structure in the Mac version is different than in the Windows version. I will try to get an emulator and fix the platform issue. I hope to have it fixed by the end of the weekend.

**Comment by CookieBadger** [comment]
Update: I tried to emulate Godot on Mac, but was unable start it. I likely will have to find someone with a Mac to fix this issue, so this might take a while. Unfortunately I cannot tell you when it will be fixed. In the meantime, I will put up a hint on the itch page.

**Comment by CookieBadger** [comment]
I just tried again on a MacBook Air (2015) with .NET 6.0, where the plugin works fine on 4.0.3 and 4.1.1 and never threw the issue, so I am thinking of removing the hint again.
Without the direct help of any of you, I won't be able to attempt any fixes for your configuration, which is why it would be important for you to contact me.

**Comment by Muini** [comment]
@CookieBadger Hey, sorry for the late replay, I did not saw your comments. I could try yesterday and I confirm it works following your above steps! (Godot 4.1.1, Macbook pro 14 (m1 pro)). Closing the issue, thank you for looking into it!

**Comment by CookieBadger** [comment]
I'm very glad it works now! Thanks!
