### ISSUE TITLE
Error in 4.1 mono modules/mono/glue/runtime_interop.cpp:1324 - System.NullReferenceException

### ISSUE THREAD

**Issue by en4ian** [CookieBadger/assetplacer-docs#6]
I don't know if you support 4.1 yet but I'm using 4.1 stable mono and this spams the console when I move my mouse. It stops if I stop moving my mouse. Any thoughts? I think it has something to do with the Terrain3D plugin. 

- scene/main/node.cpp:1511 - Index p_index = 0 is out of bounds ((int)data.children_cache.size() - data.internal_children_front_count_cache - data.internal_children_back_count_cache = 0).
- modules/mono/glue/runtime_interop.cpp:1324 - System.NullReferenceException: Object reference not set to an instance of an object.
- at AssetPlacer.ContextlessPlugin.Get3DViewports() in E:\GodotGame\example\addons\assetplacer\utils\contextlessPlugin\ContextlessPlugin.cs:line 217
- at AssetPlacer.ContextlessPlugin.GetFocused3DViewport() in E:\GodotGame\example\addons\assetplacer\utils\contextlessPlugin\ContextlessPlugin.cs:line 197
- at AssetPlacer.ContextlessPlugin._Input(InputEvent event) in E:\GodotGame\example\addons\assetplacer\utils\contextlessPlugin\ContextlessPlugin.cs:line 83
- at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 2075
- at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1293
- at AssetPlacer.ContextlessPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in E:\GodotGame\example\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\AssetPlacer.ContextlessPlugin_ScriptMethods.generated.cs:line 145
- at AssetPlacer.AssetPlacerPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in E:\GodotGame\example\Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\AssetPlacer.AssetPlacerPlugin_ScriptMethods.generated.cs:line 271
- at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24

**Comment by en4ian** [comment]
Yeah this definitely has to do with the Terrain3D plugin and this plugin. If I disable Terrain3D everything works great. As soon as I enable it the above happens.

https://github.com/outobugi/Terrain3D

**Comment by CookieBadger** [comment]
Hey @en4ian , I just uploaded a new version, that implements the compatibility with Terrain3D, thanks for reporting! Another version with a more performant integration of Terrain3D is also in the works! :)

**Comment by TokisanGames** [comment]
In the latest version, I get the first two errors even if I disable the Terrain3D plugin, and all scenes are closed, or work in a scene only with a static body plane.

```
ERROR: Index p_index = 0 is out of bounds ((int)data.children_cache.size() - data.internal_children_front_count_cache -.   at: get_child (scene/main/node.cpp:1511)
ERROR: System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetPlacer.ContextlessPlugin.<>c.<Get3DViewports>b__20_0(Node vp) in C:\GD\oota\project\addons\assetplacer\utils3   at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
   at AssetPlacer.ContextlessPlugin.GetFocused3DViewport() in C:\GD\oota\project\addons\assetplacer\utils\contextlessPl9   at AssetPlacer.ContextlessPlugin._Input(InputEvent event) in C:\GD\oota\project\addons\assetplacer\utils\contextless3   at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /r5   at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& re3   at AssetPlacer.ContextlessPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_5   at AssetPlacer.AssetPlacerPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_1   at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** arg4   at: godotsharp_pusherror (modules/mono/glue/runtime_interop.cpp:1324)
```

Also I'm able to create a new library, add an asset to it, and select it. But I cannot drag it into the viewport, regardless of scene.

**Comment by TokisanGames** [comment]
Update, I had to disable all of my plugins and found it also conflicts with Vpainter https://github.com/nx7r/Vpainter (also https://github.com/tomankirilov/VPainter). The error spam is fixed with vpainter.

With Terrain3D and debug collision enabled, it will show an asset following the mouse cursor and the terrain height, but I can't click to spawn anything.

**Comment by en4ian** [comment]
Thanks for looking into the issue

I can confirm that there are no errors when I start a blank project and include asset placer 1.0.3 and Terrain3D 0.8.2. I tested both tools in a scene and they worked together nicely. I wasn't able to use the physics/surface placement on the terrain but that's not a big deal. 

On my main project though I continue to get errors using the newer asset placer 1.0.3. Could there be some configuration setting that is causing it? I don't think it asked me about the EULA on my main project when I changed to the newer asset_placer. I'm not sure where that data would be stored

**Comment by CookieBadger** [comment]
Hello @en4ian, thanks for confirming it works! For the surface placement, I'm in touch with Tokisan about a better solution, but for now you can enable the Debug Collisions in the inspector when selecting the Terrain3D node (make sure the Terrain3D plugin is enabled), then it should also work. If the Collision Shape clutters the view, you can hide it either via the viewport or in the scene hierarchy under the terrain node.

As for your main project, make sure that you disable the plugin and press 'build' again, such that the code gets updated, I think that should fix the issue.

**Comment by en4ian** [comment]
It seems the only time assetplacer loads in my main project is when I first open it. There are errors at that time whenever I move the mouse. A lot of errors about addons\assetplacer\utils\contextlessPlugin\ContextlessPlugin.cs:line 221

I can disable the asset from the addon window
 Then
      If I do not press build
         I try to enable it then it gives me an error
     If I do press build

```
         Build succeeded.
                0 Warning(s)
                0 Error(s)
            
            Time Elapsed 00:00:02.38
```

         I try to enable it and it gives an error
         

```
scene/main/node.cpp:1511 - Index p_index = 0 is out of bounds ((int)data.children_cache.size() - data.internal_children_front_count_cache - data.internal_children_back_count_cache = 0).
  modules/mono/glue/runtime_interop.cpp:1324 - System.NullReferenceException: Object reference not set to an instance of an object.
     at AssetPlacer.ContextlessPlugin.Get3DViewports() in \addons\assetplacer\utils\contextlessPlugin\ContextlessPlugin.cs:line 221
     at AssetPlacer.ContextlessPlugin._EnterTree() in \addons\assetplacer\utils\contextlessPlugin\ContextlessPlugin.cs:line 31
     at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 2057
     at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1293
     at AssetPlacer.ContextlessPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in \Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\AssetPlacer.ContextlessPlugin_ScriptMethods.generated.cs:line 145
     at AssetPlacer.AssetPlacerPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in \Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\AssetPlacer.AssetPlacerPlugin_ScriptMethods.generated.cs:line 271
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
  modules/mono/glue/runtime_interop.cpp:1324 - System.NullReferenceException: Object reference not set to an instance of an object.
     at AssetPlacer.AssetPlacerPlugin._ProcessUpdate(Double delta) in \addons\assetplacer\AssetPlacerPlugin.cs:line 468
     at AssetPlacer.ContextlessPlugin._Process(Double delta) in \addons\assetplacer\utils\contextlessPlugin\ContextlessPlugin.cs:line 151
     at Godot.Node.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:line 2087
     at Godot.EditorPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharpEditor/Generated/GodotObjects/EditorPlugin.cs:line 1293
     at AssetPlacer.ContextlessPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in \Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\AssetPlacer.ContextlessPlugin_ScriptMethods.generated.cs:line 145
     at AssetPlacer.AssetPlacerPlugin.InvokeGodotClassMethod(godot_string_name& method, NativeVariantPtrArgs args, godot_variant& ret) in \Godot.SourceGenerators\Godot.SourceGenerators.ScriptMethodsGenerator\AssetPlacer.AssetPlacerPlugin_ScriptMethods.generated.cs:line 271
     at Godot.Bridge.CSharpInstanceBridge.Call(IntPtr godotObjectGCHandle, godot_string_name* method, godot_variant** args, Int32 argCount, godot_variant_call_error* refCallError, godot_variant* ret) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 24
  AssetPlacerPlugin: Please reload Asset Placer Plugin from the Project Settings panel!
```
 
 I might try moving all of my other files to the blank test project I made where terrain3d and assetplacer were working together. If that works then maybe some project file or addon config file broke

**Comment by CookieBadger** [comment]
@en4ian looking at how fast it builds, it seems like it doesn't really update. One thing you can do, is delete the mono folder at path-to-your-project/.godot, this way you delete all the cache. But please make sure that you actually updated the code, and don't still have version 1.0.2 installed. To check, line 214 in addons/assetplacer/utils/contextlessPlugin/ContextlessPlugin.cs should look like: `bool terrain3Dpresent = GetEditorInterface().IsPluginEnabled("terrain_3d");` If it's not, you don't have the right version.
The best would be to delete assetplacer from your addons folder as well, and drag the new version in again.
